language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install testify==0.5.2"  # TODO: make it so we can keep this in setup.py
  - "pip install  --allow-external ."
  - "python setup.py test"
# command to run tests
script: make test
